config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'trips/index'
  root to: "trips#index"
  resources :trips, only: [:index, :create, :new, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
  has_many_attached :images
  has_many :trips, through: :trip_points
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :points, through: :trip_points
end

app/models/trip_point.rb
# こっちは中間テーブル

class TripPoint < ApplicationRecord
  belongs_to :trip
  belongs_to :point
end

app/models/trips_point.rb
# こっちはFormオブジェクト用のモデル

class TripsPoint
  include ActiveModel::Model
  attr_accessor :trip_date, :trip_title, :trip_comment, :user_id, :address, :point_comment, :images,
                :trip_id, :point_id

  # delegate :persisted?, to: :item

  def initialize(attributes = nil, trip: Trip.new)
      @trip = trip
      # attributes ||= default_attributes
      # super(attributes)
  end

  # saveはとりあえず簡易的なものを使用
  def save
    # 旅行情報を保存し、変数tripに代入する
    trip = Trip.create(trip_date: trip_date, trip_title: triptitle, trip_comment: tripcomment, user_id: user_id)
    # 旅行先１を保存する
    # donation_idには、変数donationのidと指定すると書いてあるのでtrip_idをとりあえず記述してみたが、そんなカラムは作っていないしおそらく不要
    Point.create(address: address, point_comment: point_comment, trip_id: trip.id)
  end

  # def save
  #    return if invalid?
  #    ActiveRecord::Base.transaction do
  #     tags = split_tag_names.map { |tag_name| Tag.find_or_create_by!(tag_name: tag_name) }
  #     item.update!(name: name, info: info, category_id: category_id, sales_status_id: sales_status_id,
  #     shipping_fee_status_id: shipping_fee_status_id, prefecture_id: prefecture_id, scheduled_delivery_id: scheduled_delivery_id, price: price,user_id: user_id, image: image,tags: tags)
  #    end
  # rescue ActiveRecord::RecordInvalid
  #     false
  # end

  # def to_model
  #   item
  # end

  # private

  # attr_reader :item

  # def default_attributes
  #   {
  #     name: item.name,
  #     info: item.info,
  #     category_id: item.category_id,
  #     sales_status_id: item.sales_status_id,
  #     shipping_fee_status_id: item.shipping_fee_status_id,
  #     prefecture_id: item.prefecture_id,
  #     scheduled_delivery_id: item.scheduled_delivery_id,
  #     price: item.price,
  #     user_id: item.user_id,
  #     image: item.image,
  #     tag_name: item.tags.pluck(:tag_name).join(',')
  #   }
  # end

  # def split_tag_names
  #   tag_name.split(',')
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
  end

  def new
    # @point = Point.new
    @trip_point = TripsPoint.new
  end

  def create
    @trip_point = TripsPoint.new(point_params)
    if @trip_point.valid? 
      @trip_point.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  private
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def point_params
    params.require(:trip_point).permit(:trip_date, :trip_title, :trip_comment, :address, :point_comment, images: []).merge(:trip_id,:point_id,:user_id)
  end

  # def point_params
  #   params.require(:point).permit(:address, :point_comment, images: [])
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prototrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <%= link_to "投稿する", new_user_session_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規ユーザー登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>

    <%= yield %>
    
  </body>
</html>

app/views/trips/index.html.erb
<%= link_to '新しい旅の記録', new_trip_path %>

app/views/trips/new.html.erb
<div class="main-background">
  <div class="left-side">
  ここに地図
  
  <%# <script src="https://maps.googleapis.com/maps/api/js?key=ここにAPIKEY&callback=initMap" async defer></script> %>
  </div>


  <div class="right-side">
  ここにデータ入力
    <div class="maps-main">
      <%= form_with model: @trip_point, url: trips_path, method: :post, local: true do |f| %>
        <%# 旅 タイトル入力  詳細未定%>
            <div class="weight-bold-text">
              旅タイトル
            </div>
            <%= f.text_area :trip_title, class:"maps-text", id:"maps-address", placeholder:"旅タイトル" %>
        <%# /旅 タイトル入力 詳細未定 %>

        <%# 旅 コメント入力 詳細未定%>
            <div class="weight-bold-text">
              旅コメント
            </div>
            <%= f.text_area :trip_title, class:"maps-text", id:"maps-address", placeholder:"旅コメント" %>
        <%# /旅 コメント入力  詳細未定 %>


        <div class="trip_point">
          <%# 住所入力 %>
              <div class="weight-bold-text">
                住所
              </div>
              <%= f.text_area :address, class:"maps-text", id:"maps-address", placeholder:"住所" %>
          <%# /住所入力 %>

          <%# コメント入力 %>
                <div class="weight-bold-text">
                  おすすめポイント
                </div>
                <%= f.text_area :point_comment, class:"maps-text", id:"maps-comment", placeholder:"ポイントの説明（必須 1,000文字まで）訪れたポイントの見どころ、おすすめ商品、裏話などを書き込んでください" ,rows:"7" ,maxlength:"1000" %>
          <%# /コメント入力 %>

          <%# 画像 %>
            <div class="img-upload">
              <div class="weight-bold-text">
                画像
              </div>
              <div class="click-upload">
                <p>
                  クリックしてファイルをアップロード
                </p>
                <%= f.file_field :images, name: 'message[images][]', id:"message_image" %>
              </div>
              <div id="image-list"></div>
            </div>
          <%# /画像 %>
        </div>

        <%= f.submit '投稿する' %>
      <% end %>
      <%# <%= image_tag @point.image, id: 'image' if @point.image.present? %>

      <%# 単一のときはこれで複数画像保存ができていたが。。。フォームオブジェクトにimagesがないのが原因か
      eachがおかしいと言われた→配列になっていないか
      タグを複数検索したときのような特殊な記述が必要になりそう

      単一保存の時
      <% @point.images.each do |image| %>
        <%# <%= image_tag image, class: 'images' %>
      <%# <% end %> 

      <% @trip_point.images.each do |image| %>
        <%= image_tag image, class: 'images' %>
      <% end %>
    </div>  
  </div>


</div>